### ISSUE TITLE
Variadic assertions and custom messages

### ISSUE THREAD

**Issue by terinjokes** [bigpipe/assume#5]
The standard bag of assertions tend to come come in the following form: a function that accepts a pre-determined or easily determinable at runtime number of arguments (such as `throw`), with a custom message as the last parameter. It's also what's documented:

>  If you want the failed assertion to include a custom message or reason you can **always** add this as last argument of the assertion function.

I wanted to keep the feel of the standard assertions in my plugins: they should feel apart of the ecosystem, rather than something foreign that happens to work. So for anything that could be variadic, I'm accepting an array as the first parameter.

There is one exception in the standard assertions that questions this assumption: `either`. It's the only true variadic in the standard library, and it's also the only assertion that doesn't accept a custom message.

(The other exception, a nit-pick, is `eql`, but it's not documented to accept the `slice` parameter, and it's [correctable](https://github.com/bigpipe/assume/issues/3#issuecomment-70387373).)

I have a preference to not challenge user assumptions, and have all methods accept the custom message parameter, even if it requires more arrays. But I wanted your input on how I should proceed.

**Comment by 3rd-Eden** [comment]
I personally find:

```js
assume('foo').is.either('bar', 'foo', 'banana');
```

Easier to read and write than:

```js
assume('foo').is.either(['foo, 'bar', 'baz]);
```

As the example above could also mean that it should be an array instead of one of the strings that are present in the array. Especially when you start doing `deep` equals of array using either:

```js
assume(['foo']).is.deep.either([['bar'], ['foo'], 'bar']);
assume(['foo']).is.deep.either(['bar'], ['foo'], 'bar');
```

But I do understand you point and this API is less than ideal. And I don't really an other option forcing an array structure if we want all API methods to follow the same argument structure.

As for the somewhat "private" slice argument, it has been [removed](6ed324c6c2736ed6a56d1f0476851290b87e860f) from the `eql` method now that I introduced a `sliceStack` option in #3.
