### ISSUE TITLE
Object thrown in NodeJS

### ISSUE THREAD

**Issue by terinjokes** [bigpipe/assume#7]
The thing thrown between browsers and NodeJS are different: in browsers an Error instance is thrown, whereas in NodeJS an object is thrown. Is there a particular reason an [`AssertionError`](https://github.com/chaijs/assertion-error) couldn't be thrown in both cases?

**Comment by 3rd-Eden** [comment]
The biggest problem I had with AssertionError is that is uses ES5 methods in order to create an Error like object which will stil have a stacktrace. These will obviously not work in older browsers that do not support Object.create. These are still browsers I would like to support with assume so the only option i've found was to throw an `object` instead of an `err` instance so you atleast have access to the `stack` and `message` of the assertion error. 

I would love to know if there are better ways to solve this as I'm really not pleased with the current solution either but that was I could come up with.

**Comment by 3rd-Eden** [comment]
Oh wait, the Object is thrown in Nodejs not browsers, sorry about that. I'm gonna list this as a bug and see if we can create a better solution for this like inheriting from a Error instance as Assertion-Error is doing.

**Comment by 3rd-Eden** [comment]
Added feature detection for `Object.create` so we can create a custom error instance **with** the correct stack trace. This will land in `1.2.0` which i'll release somewhere today.
